name = "pgcl"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["HeyVL"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
# autoImplicit = false
linter.docPrime = false
linter.hashCommand = true
linter.oldObtain = true
linter.style.cases = true
linter.style.cdot = true
linter.style.docString = true
linter.style.dollarSyntax = true
linter.style.header = true
linter.style.lambdaSyntax = true
linter.style.longLine = true
linter.style.missingEnd = true
linter.style.multiGoal = true
linter.style.openClassical = true
linter.style.refine = true
linter.style.setOption = true

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "PGCL"

[[lean_lib]]
name = "MDP"

[[lean_lib]]
name = "STDX"

[[lean_lib]]
name = "HeyVL"
